services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

